### PR TITLE
Added a java program

### PR DESCRIPTION
**Pull request by Muazzy**
added a java program which prints  Fibonacci series

### CODE REVIEW

**Comment by kevinbhingaradiya** [comment]
Give me some time I accept your request and don't worry about the time when
I accpt request your time is reduced

**Comment by Muazzy** [comment]
Sure bro thanks

**Comment by kevinbhingaradiya** [comment]
Hay buddy I will send you one more repo link that's is more eligible repo.
And also some rules changed so
https://github.com/kevinbhingaradiya/Hacktoberfest

**Review by kevinb9819 — APPROVED** [review]

**Comment by kevinbhingaradiya** [comment]
OK bro if you want more PRs then you use that repo ok

**Comment by kevinbhingaradiya** [comment]
OK than you want more PRs then you send me today's repo link that is as per
new rules

**Comment by Muazzy** [comment]
sure all set

**Pull request closed without merging**
